### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte X in position X: ordinal not in range

### ISSUE THREAD

**Issue by raspher** [ArchiveTeam/ftp-queue#4]
Traceback (most recent call last):
  File "ftp_check.py", line 64, in <module>
    for line in index.read().splitlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 232045: ordinal not in range(128)

when gathering info from ftp://ftp.isc.org/ as a single-line file /todo/

**Comment by Gapstare** [comment]
Still an issue and a show stopping bug it seems.
